### ISSUE TITLE
Resources are not being loaded

### ISSUE THREAD

**Issue by kodbilenadam** [RCVolus/lol-pick-ban-ui#10]
![image](https://user-images.githubusercontent.com/7461799/82377192-fdc46800-9a2b-11ea-8871-c7fd7fe9302d.png)

URL for overlay.png `http://localhost:5000/layouts/underlay.png` but it should be `http://localhost:5000/layout-simple/underlay.png`

This issue is happening both simple-layout & layout-volu-europe

**Comment by kodbilenadam** [comment]
> ![image](https://user-images.githubusercontent.com/7461799/82377192-fdc46800-9a2b-11ea-8871-c7fd7fe9302d.png)
> 
> URL for overlay.png `http://localhost:5000/layouts/underlay.png` but it should be `http://localhost:5000/layout-simple/underlay.png`
> 
> This issue is happening both simple-layout & layout-volu-europe

You can fix this for simple-layout by adding `layout-simple/` right before the paths of the resources but 
![image](https://user-images.githubusercontent.com/7461799/82378170-619b6080-9a2d-11ea-841f-b4a3538dd383.png)
the script is still not connecting to the ws

**Comment by LarsBaertschi** [comment]
Could you try using this link to open up the website: http://localhost:5000/layouts/layout-simple/index.html?backend=ws://localhost:8999

**Comment by kodbilenadam** [comment]
> Could you try using this link to open up the website: http://localhost:5000/layouts/layout-simple/index.html?backend=ws://localhost:8999
> 
> Please also pay attention that the europe layout has seperate install instructions: https://github.com/RCVolus/lol-pick-ban-ui#installation-of-europe-layout

I am using the link you provided both here and README to reach that site. Also when I tried to serve Europe layout it didn't work either.

**Comment by LarsBaertschi** [comment]
Sorry, I provided a wrong link. Does it work with http://localhost:5000/layouts/layout-simple/?backend=ws://localhost:8999 ? (so the one in the README also seems to be wrong).

For the Europe layout, you do not need to use any `serve` command (unless you built it). It is easier to just start the development server using `npm start`, as described in the README section "Installation of europe layout". If you have any issues there please let me know!
