### ISSUE TITLE
issues npm install

### ISSUE THREAD

**Issue by siropregno** [RCVolus/lol-pick-ban-ui#109]
i tried npm install and i'm gettting this  :/ am i doing it wrong?

npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\sirop\Desktop\lol-pick-ban-ui-master\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\sirop\Desktop\lol-pick-ban-ui-master\package.json'
npm WARN lol-pick-ban-ui-master No description
npm WARN lol-pick-ban-ui-master No repository field.
npm WARN lol-pick-ban-ui-master No README data
npm WARN lol-pick-ban-ui-master No license field.

up to date in 1.329s
found 0 vulnerabilities

PS C:\Users\sirop\Desktop\lol-pick-ban-ui-master>

**Comment by Grayknife** [comment]
Hello @siropregno 
the dev team moved files around on last patch, so you have to run `npm install` in the **backend** folder (before patch it was the root folder). Second `npm install` has to be executed in layouts > layout-volu-europe (frontend).
