### ISSUE TITLE
Installation successful and europe layout doesn't work

### ISSUE THREAD

**Issue by Haruu3123** [RCVolus/lol-pick-ban-ui#112]
![image](https://user-images.githubusercontent.com/91402869/134806209-3d4095d7-0783-4ffe-b507-a4e9a87df665.png)
![image](https://user-images.githubusercontent.com/91402869/134806213-162bd8bf-503d-440f-ae7f-416dc8d6287a.png)
![image](https://user-images.githubusercontent.com/91402869/134806266-aceb5cf4-f2dc-4913-81ff-27ecc9e323af.png)
![image](https://user-images.githubusercontent.com/91402869/134806276-8c9ee1bf-a13f-42d6-839e-8ea02dd277d9.png)
overlay doesn't work,help me fix this

**Comment by LarsBaertschi** [comment]
Hey, can you check if during you run the pick-ban, is there any log line on the backend indicating that the champ select was started?

Maybe it's as simple as focusing the backend Powershell window and pressing the "enter" key.

**Comment by Himyu** [comment]
It seems you are not running the [RCVolus/league-observer-tool](https://github.com/RCVolus/league-observer-tool) or do you?
