### ISSUE TITLE
npm command not working at all

### ISSUE THREAD

**Issue by Braiwnz** [RCVolus/lol-pick-ban-ui#115]
First of all: im not very experienced with coding.

I used your Overlay, it worked great. 2nd time I opened the Powershell to initiate it, I got syntaxErrors on the Localhost Website. 
Something about line 38, but It wouldnt let me open the file.

So I tried to delete everything and re-install/re-download. 
Now I'm in deep trouble: Whenever I open the Powershell and try to use **any** npm command, Windows is asking me what program I want to use to "open the file", for example note pad, word etc.. It does not matter if I write "npm install" or "npm start" or just "npm", nor where I open the Powershell.

I think I manually deletet some "npm" files next to the Node files, but didn't do so after re-installing.

I'm really looking forward to using your overlay for future Tournament Casts, its by far the cleanest one out there imo. 

Thanking for any help in advance,
stay healthy
stay happy

**Comment by sdomi4** [comment]
Hi Braiwnz

It seems like you deleted npm itself accidentally.
Did you also uninstall & reinstall node.js? This should include npm, you may be able to fix the issue by doing this
