### ISSUE TITLE
Error: EBADPLATFORM

### ISSUE THREAD

**Issue by Kaboommmm** [RCVolus/lol-pick-ban-ui#117]
![Screenshot Error EBADPLATFORM](https://user-images.githubusercontent.com/94870791/142935310-cb40c523-ac3c-48f8-88e9-697520d0249d.jpg)

Hello, 
I was able to install the backend folder data, but when it came to the layout-volu-europe ones, this error came up and I was not able to fix it at all. Any helps?

Kind regards.

**Comment by Kaboommmm** [comment]
It may be because "darwin" is usually not for Windows (if I remember correctly), but for another operating system. As I am working with Windows, this may not work for me. But I am not sure of course.

**Comment by sdomi4** [comment]
This issue is probably related to the version of node.js installed, which version are you running? We last tested on 16.7, please try up/downgrading node.js if your version differs

**Comment by Kaboommmm** [comment]
I downloaded the version at the project page. Isn't this the right one? If not, could you send me the version I should download? That would be very great!

**Comment by sdomi4** [comment]
You can download node.js 16.7.0 here: https://nodejs.org/download/release/v16.7.0/node-v16.7.0-x64.msi

I have updated the readme accordingly.

**Comment by Kaboommmm** [comment]
Thank you, I will try to fix it with this!

**Comment by Kaboommmm** [comment]
Worked, thank you!
