### ISSUE TITLE
no config file

### ISSUE THREAD

**Issue by aluhrain** [RCVolus/lol-pick-ban-ui#119]
Hello! I cannot seem to find the config file needed to edit the team name and coach name and theme colors? do I need to make one myself? I installed the europe layout

**Comment by sdomi4** [comment]
Hi aluhrain

You should be able to find the config in \lol-pick-ban-ui\backend – if the file isn't present there you can grab the default config here (this should be included if you downloaded the whole folder, so it might be worth redownloading in case other files are missing as well):  https://github.com/RCVolus/lol-pick-ban-ui/blob/master/backend/config.json
