### ISSUE TITLE
Out of order

### ISSUE THREAD

**Issue by Khhd1** [RCVolus/lol-pick-ban-ui#120]
![image](https://user-images.githubusercontent.com/82941693/147208871-4737702c-24f5-4315-8777-e84c91cd96ea.png)

And I learned a message: after the update of the game version, LCU no longer uses lockfile to store information such as token and port. As a result, some third-party tools that read lockfile and call LCU API cannot obtain token and port.

**Comment by sdomi4** [comment]
Hi Khhd1

This error commonly occurs when the League Client process is running as administrator, but the pick-ban-ui is running in a user context. Please try launching the backend and frontend as an administrator.

We are not affiliated with vigilant-bans, if the installer doesn't work, please try installing the pick-ban-ui directly and running it as admin, as described in the readme.

We are not aware of any changes being made to the lockfile method, and I am unable to reproduce the issue or find any info. If you have any links you could share I would be grateful :)
