### ISSUE TITLE
npm install backend Issues

### ISSUE THREAD

**Issue by LittleHoller** [RCVolus/lol-pick-ban-ui#128]
What can i do? Or Whats the Problem?

--------------
After npm install: 

up to date, audited 596 packages in 1s

21 vulnerabilities (2 low, 11 moderate, 8 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

What can i do? Or Whats the Problem?

**Comment by LittleHoller** [comment]
![image](https://user-images.githubusercontent.com/101972307/159157885-f625c19a-8484-4fdf-88a3-0e892b0246ee.png)

**Comment by sdomi4** [comment]
Hi there

This message only notes some out of date packages which are included in the pick ban UI and has no impact on functionality.
If you are only looking to use the P&B UI, you don't need to do anything, but if you want to fix the dependency issues feel free to submit a pull request ;)
