### ISSUE TITLE
Simple layout

### ISSUE THREAD

**Issue by getwh1ted** [RCVolus/lol-pick-ban-ui#13]
Simple layout is just not working

**Comment by LarsBaertschi** [comment]
Please provide more details, especially reproduction steps. The simple layout works on my end as intended.

**Comment by getwh1ted** [comment]
I'm following every step but it's stuck like this
![image](https://user-images.githubusercontent.com/48430352/83353826-57defa80-a355-11ea-91ae-a5fa93af8f12.png)
![image](https://user-images.githubusercontent.com/48430352/83353829-5c0b1800-a355-11ea-8a57-dc448eb0306b.png)
![image](https://user-images.githubusercontent.com/48430352/83353832-5e6d7200-a355-11ea-9435-7ee07cbb4cc3.png)

**Comment by LarsBaertschi** [comment]
Hey, I'm unable to reproduce the issue you mentioned.

In what directory do you execute the `serve` command? It should be in the root directory.

Else for further analysis, what do you get if you open up `http://localhost:5000`?

**Comment by getwh1ted** [comment]
you can see that, it's in layout directory

**Comment by getwh1ted** [comment]
okay now it's working

**Comment by shinilee** [comment]
hey shir0xyz I'd like to use simple layout just like you but I'm having same problem how did you solve it?
