### ISSUE TITLE
error: failed to read backend url query param. make sure you set ?backend=ws://[ip]:[port] as query parameter.

### ISSUE THREAD

**Issue by jdjoswald** [RCVolus/lol-pick-ban-ui#132]

**Comment by Laraakaa** [comment]
Hey there!
Have you made sure, that you set ?backend=ws://[ip]:[port] as query parameter?
Also, check this out: https://github.com/RCVolus/lol-pick-ban-ui#syntaxerror-failed-to-construct-websocket-the-url-undefined-is-invalid (we have recently changed the error message yielded to something more clear)
