### ISSUE TITLE
Error when starting backend

### ISSUE THREAD

**Issue by jackychu2020** [RCVolus/lol-pick-ban-ui#137]
Error: connect ECONNREFUSED 127.0.0.1:65461
![image](https://user-images.githubusercontent.com/73355923/166553590-26e8fd70-15fd-4ba8-92b1-6c6d5d0a57eb.png)

**Comment by sdomi4** [comment]
Hello :)

It looks like the league client wasn't open when you started the backend. Starting the client before the backend should aviod this issue.

**Comment by jackychu2020** [comment]
> Hello :)
> 
> It looks like the league client wasn't open when you started the backend. Starting the client before the backend should aviod this issue.

I tried again recently. I started my client before running backend, and it still remained this error.

**Comment by sdomi4** [comment]
Is it possible the league client is running in an Administrator context (or is it the Garena client?). In that case, the backend also needs to be running in an admin context (as described [here](https://github.com/RCVolus/lol-pick-ban-ui#connection-to-league-client-failed-unhandled-promiserejectionwarning-typeerror-cannot-read-property-port-of-undefined))

**Comment by jackychu2020** [comment]
> Is it possible the league client is running in an Administrator context (or is it the Garena client?). In that case, the backend also needs to be running in an admin context (as described [here](https://github.com/RCVolus/lol-pick-ban-ui#connection-to-league-client-failed-unhandled-promiserejectionwarning-typeerror-cannot-read-property-port-of-undefined))

by the way, is Lord Dominik's Regards named after you? lol

**Comment by sdomi4** [comment]
Same issue as #138; updates will be provided there. Closing this issue. 
(No relation to Lord Dominik, no idea who they based that one on :))
