### ISSUE TITLE
Error when starting backend

### ISSUE THREAD

**Issue by M-BAXI** [RCVolus/lol-pick-ban-ui#138]
Hello, I'm sorry to bother you. However, when I run the backend, error: connect econnreused 127.0.0.1:59072 appears, as shown in the figure.

I have checked that PowerShell and the client are running as administrator.

Is it because of the use of Tencent game client?

Do you need to link the specified agent client?

Or something else?

![屏幕截图 2022-05-05 203734](https://user-images.githubusercontent.com/83072937/166924469-cad32551-35bb-4e00-9f95-589118fab08a.png)

This is an error when using the old version. In the latest version, I didn't find the package JSON this file. After copying the old version and executing NPM install and NPM start, the error content as shown in the figure appears. How should this be solved?
![屏幕截图 2022-05-05 213406](https://user-images.githubusercontent.com/83072937/166934511-be8e675e-f6a2-47a3-8376-8c5f418be80b.png)

**Comment by M-BAXI** [comment]
> 我有同样的问题。
I saw it. I think it may be the ghost of Tencent that makes us in China unable to link to this address

**Comment by jackychu2020** [comment]
> > 我有同样的问题。
> > I saw it. I think it may be the ghost of Tencent that makes us in China unable to link to this address

马化腾你 妈什么时候 啊？

**Comment by M-BAXI** [comment]
> > > 我有同样的问题。
> > > I saw it. I think it may be the ghost of Tencent that makes us in China unable to link to this address
> 
> 马化腾你 妈什么时候 啊？


> > > 我有同样的问题。
> > > I saw it. I think it may be the ghost of Tencent that makes us in China unable to link to this address
> 
> 马化腾你 妈什么时候 啊？

或许可以尝试用VPN直接去riotgame下游戏国际端也许可以用，就是不知道能不能用来ob国服的比赛。我是真的很想办一场学校的比赛，但是没有这个UI，还有那些直播转场动效。头都大了现在😵

**Comment by jackychu2020** [comment]
> > > > 我有同样的问题。
> > > > I saw it. I think it may be the ghost of Tencent that makes us in China unable to link to this address
> > 
> > 
> > 马化腾你 妈什么时候 啊？
> 
> > > > 我有同样的问题。
> > > > I saw it. I think it may be the ghost of Tencent that makes us in China unable to link to this address
> > 
> > 
> > 马化腾你 妈什么时候 啊？
> 
> 或许可以尝试用VPN直接去riotgame下游戏国际端也许可以用，就是不知道能不能用来ob国服的比赛。我是真的很想办一场学校的比赛，但是没有这个UI，还有那些直播转场动效。头都大了现在😵

试过了 澳服不行

**Comment by jackychu2020** [comment]
> > > > > 我有同样的问题。
> > > > > I saw it. I think it may be the ghost of Tencent that makes us in China unable to link to this address
> > > 
> > > 
> > > 马化腾你 妈什么时候 啊？
> > 
> > 
> > > > > 我有同样的问题。
> > > > > I saw it. I think it may be the ghost of Tencent that makes us in China unable to link to this address
> > > 
> > > 
> > > 马化腾你 妈什么时候 啊？
> > 
> > 
> > 或许可以尝试用VPN直接去riotgame下游戏国际端也许可以用，就是不知道能不能用来ob国服的比赛。我是真的很想办一场学校的比赛，但是没有这个UI，还有那些直播转场动效。头都大了现在😵
> 
> 试过了 澳服不行

或许直接用客户端的bp界面也行

**Comment by M-BAXI** [comment]
> > > > > > 我有同样的问题。
> > > > > > I saw it. I think it may be the ghost of Tencent that makes us in China unable to link to this address
> > > > 
> > > > 
> > > > 马化腾你 妈什么时候 啊？
> > > 
> > > 
> > > > > > 我有同样的问题。
> > > > > > I saw it. I think it may be the ghost of Tencent that makes us in China unable to link to this address
> > > > 
> > > > 
> > > > 马化腾你 妈什么时候 啊？
> > > 
> > > 
> > > 或许可以尝试用VPN直接去riotgame下游戏国际端也许可以用，就是不知道能不能用来ob国服的比赛。我是真的很想办一场学校的比赛，但是没有这个UI，还有那些直播转场动效。头都大了现在😵
> > 
> > 
> > 试过了 澳服不行
> 
> 或许直接用客户端的bp界面也行

咱想做直转播呐，你可以看下抖音里日照电竞的录播，我想搞那种跟s11那样正式的直播界面，客户端的bp太没观感了

**Comment by jackychu2020** [comment]
> > > > > > > 我有同样的问题。
> > > > > > > I saw it. I think it may be the ghost of Tencent that makes us in China unable to link to this address
> > > > > 
> > > > > 
> > > > > 马化腾你 妈什么时候 啊？
> > > > 
> > > > 
> > > > > > > 我有同样的问题。
> > > > > > > I saw it. I think it may be the ghost of Tencent that makes us in China unable to link to this address
> > > > > 
> > > > > 
> > > > > 马化腾你 妈什么时候 啊？
> > > > 
> > > > 
> > > > 或许可以尝试用VPN直接去riotgame下游戏国际端也许可以用，就是不知道能不能用来ob国服的比赛。我是真的很想办一场学校的比赛，但是没有这个UI，还有那些直播转场动效。头都大了现在😵
> > > 
> > > 
> > > 试过了 澳服不行
> > 
> > 
> > 或许直接用客户端的bp界面也行
> 
> 咱想做直转播呐，你可以看下抖音里日照电竞的录播，我想搞那种跟s11那样正式的直播界面，客户端的bp太没观感了

不瞒你说 鄙人不才 做过fpx粉丝联赛的导播
我用的obs 和客户端自带的功能
效果如下 可以参考一下
https://www.bilibili.com/video/BV1234y1Y7hg?spm_id_from=333.999.0.0

**Comment by M-BAXI** [comment]
> > > > > > > > 我有同样的问题。
> > > > > > > > I saw it. I think it may be the ghost of Tencent that makes us in China unable to link to this address
> > > > > > 
> > > > > > 
> > > > > > 马化腾你 妈什么时候 啊？
> > > > > 
> > > > > 
> > > > > > > > 我有同样的问题。
> > > > > > > > I saw it. I think it may be the ghost of Tencent that makes us in China unable to link to this address
> > > > > > 
> > > > > > 
> > > > > > 马化腾你 妈什么时候 啊？
> > > > > 
> > > > > 
> > > > > 或许可以尝试用VPN直接去riotgame下游戏国际端也许可以用，就是不知道能不能用来ob国服的比赛。我是真的很想办一场学校的比赛，但是没有这个UI，还有那些直播转场动效。头都大了现在😵
> > > > 
> > > > 
> > > > 试过了 澳服不行
> > > 
> > > 
> > > 或许直接用客户端的bp界面也行
> > 
> > 
> > 咱想做直转播呐，你可以看下抖音里日照电竞的录播，我想搞那种跟s11那样正式的直播界面，客户端的bp太没观感了
> 
> 不瞒你说 鄙人不才 做过fpx粉丝联赛的导播 我用的obs 和客户端自带的功能 效果如下 可以参考一下 https://www.bilibili.com/video/BV1234y1Y7hg?spm_id_from=333.999.0.0

您有联系方式嘛!可以教教我怎么搞这些东西嘛🥺

**Comment by sdomi4** [comment]
We suspect this is a problem with the tencent client, there are apparently some differences in how the LCU API is handled.
Could you try starting the backend with `npm start -- --debug --experimentalConnector`? This might give us some more info on what is going wrong.

**Comment by M-BAXI** [comment]
I have tried to use this instruction and the contents are shown in the figure 
![微信图片_20220506072948](https://user-images.githubusercontent.com/83072937/167043124-66bbc902-3e77-44e5-b13b-6672503aaa83.png)

**Comment by M-BAXI** [comment]
> [微信图片_20220506072948](https://user-images.githubusercontent.com/83072937/167043124-66bbc902-3e77-44e5-b13b-6672503aaa83.png)

**Comment by M-BAXI** [comment]
> We suspect this is a problem with the tencent client, there are apparently some differences in how the LCU API is handled. Could you try starting the backend with `npm start -- --debug --experimentalConnector`? This might give us some more info on what is going wrong.
I have tried to use this instruction ,and the contents are shown in the figure 
![微信图片_20220506072948](https://user-images.githubusercontent.com/83072937/167043412-bf29195c-5213-4f99-8142-e00cf21d8c85.png)
