### ISSUE TITLE
Deploy Apliccation

### ISSUE THREAD

**Issue by daisukedd** [RCVolus/lol-pick-ban-ui#146]
Layout runs on url [[http://localhost:3000?backend=ws://localhost:8999](http://localhost:3000/?backend=ws://localhost:8999)](url) , how can i upload this url to the web and allow other people outside the network access to the link?

**Comment by sdomi4** [comment]
The Tool should automatically bind to every interface on the device running it. If you need to view the UI from outside the local network, there are a few options:
- Recommended: Extend your local network with VPN/SD-WAN; we sometimes use ZeroTier for this in our own productions
- Alternatively: Set up port forwarding on your router to make the needed Ports (3000 and 8999) available from the internet
- Not recommended, but workable: Assign the device a public IP address (if you happen to have spares)

If you are running a remote production, you might also want to give our Prod-Toolkit a look, it includes a port of this UI and is built with remote productions in mind.

**Comment by daisukedd** [comment]
Interesting, I'll look into these tools. I broadcast the draft remotely via **SRT**, but the internet quality doesn't help, so I wanted to send the URL directly to the streamer. Do you have a step by step on how to configure it?
