### ISSUE TITLE
Cant Install Europe Layout 

### ISSUE THREAD

**Issue by asyuki1** [RCVolus/lol-pick-ban-ui#148]
Hey. I cant install the Layout Volu Europe. I Always get a Error. Idk what to do.
The Bracked UI Works but not the Layout. The YT Vid does not Help me at all.
![811609243144caa4fe38ef23dea1a1f4](https://user-images.githubusercontent.com/108884282/177839569-99f7c719-489e-43ba-93e1-839e9d7dca4b.png)

**Comment by sdomi4** [comment]
Duplicate from #147
