### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by Nahnudul** [RCVolus/lol-pick-ban-ui#151]
can someone drop or send me the new installation process video? It will be very helpful to me.
cause I follow all the steps and the overlay didn't pop up when the champ select happed.

**Comment by daisukedd** [comment]
start with vscode terminal

**Comment by Nahnudul** [comment]
did you fully install it then please take a record and share the video link with me plz. plz. plz.

**Comment by daisukedd** [comment]
do you have discord? pass I call

**Comment by Nahnudul** [comment]
WhipFist1#6987
my discord name.
add me and I am from Bangladesh.

**Comment by daisukedd** [comment]
add you on discord
