### ISSUE TITLE
Fail to install

### ISSUE THREAD

**Issue by ZipScorpion** [RCVolus/lol-pick-ban-ui#153]
Hi i trying to install it but say me error. i share the pict.

I have the complete file downloaded in zip, when executing the shell and installing, I get that error

![image](https://user-images.githubusercontent.com/114967068/193717545-09870095-a699-421f-8fcd-57c1aa5cccfc.png)

**Comment by sdomi4** [comment]
Please make sure you run the `npm install` command inside the `backend` folder (and the `layouts/layout-volu-europe` folder). If in doubt, pelase refer to the installation instructions in the [readme](https://github.com/RCVolus/lol-pick-ban-ui#installation-development-purposes).

**Comment by ZipScorpion** [comment]
Thanks you, now working
