### ISSUE TITLE
ReactDevUtils / volu-europe layout not starting

### ISSUE THREAD

**Issue by stXwinter** [RCVolus/lol-pick-ban-ui#154]
Encountered this error whilst launching up volu-europe layout using npm start.

![image](https://user-images.githubusercontent.com/44768100/196031700-2a5dbf84-ad39-459c-a975-ee63c2742e3b.png)
![unknown](https://user-images.githubusercontent.com/44768100/196031718-96075757-96c5-498f-9e74-54d77b843712.png)

Note: At first it worked but images were unknown and font stuck in times new roman.

**Comment by stXwinter** [comment]
Also getting this error whilst trying to reinstall fresh

![Capture](https://user-images.githubusercontent.com/44768100/196032076-1372949e-3218-4f46-b60a-2ac4f725b697.PNG)

**Comment by sdomi4** [comment]
Could you check which version of node you are running? (`node -v`)

**Comment by stXwinter** [comment]
> Could you check which version of node you are running? (`node -v`)

v16.17.1

**Comment by sdomi4** [comment]
We develop and test on node 16.7, so your results may differ from ours.
I don't see a reason why it shouldn't work on 16.17 once npm is updated.
Please try the following steps:
- Run `npm install -g npm`
- Run `npm ci` in the `\backend` and `\layouts\volu-europe` folders
- Run `npm start` in both directories

**Comment by stXwinter** [comment]
Unfortunately still having errors.

**Running "npm ci" in "C:\Users\avera\Desktop\lol-pick-ban-ui-master\backend"**
![backend](https://user-images.githubusercontent.com/44768100/196133407-902b7019-15d9-475c-8c15-139999243955.PNG)

**Running "npm ci" in "C:\Users\avera\Desktop\lol-pick-ban-ui-master\layouts\layout-volu-europe"**
![volu-europe](https://user-images.githubusercontent.com/44768100/196133619-ece3dc7b-248b-4222-a056-95b86ffdd902.PNG)

RUNNING THE NPM START:

Running NPM start in both directories:
![p and b ui](https://user-images.githubusercontent.com/44768100/196133845-187c7d95-48e9-4980-92b3-bd1fab68842a.PNG)

![same error](https://user-images.githubusercontent.com/44768100/196133897-74c6a3f6-7755-4662-a730-957a5ce66bc9.PNG)

**Comment by stXwinter** [comment]
Should I update my node.js?

**Comment by sdomi4** [comment]
The warnings with the `npm ci` commands are to be expected and shouldn't affect functionality.
I am unable to reproduce these issues with node 16.7; could you try changing your node version (download is linked in the readme)?

**Comment by stXwinter** [comment]
A later version of node is installed, should I uninstall this version and hop back on 16.7 (linked in readme)

![image](https://user-images.githubusercontent.com/44768100/196148132-0b258800-dfcb-40b9-bf5a-4986f947e890.png)

**Comment by sdomi4** [comment]
Yes, unless you need node 16.17 for something else. Both the pick-ban-ui and the prod-toolkit are built and tested on node 16.7
