### ISSUE TITLE
Graphics are not loading

### ISSUE THREAD

**Issue by TheLines** [RCVolus/lol-pick-ban-ui#156]
I installed the tool today again, since i am starting to cast again. But i encountered a weird bug, where none of the champs or summonerspells were loading, except for the champs up to Annie, but not anivia. 
![image](https://user-images.githubusercontent.com/85252700/200642955-731c3224-f67e-46e6-977a-60454c0eea66.png)

**Comment by sdomi4** [comment]
The download might have been wonky for some reason, could you try forcing a redownload by deleting the folders inside `...\lol-pick-ban-ui\backend\cache` and seeing if it helps after a restart?

**Comment by TheLines** [comment]
i will try

**Comment by TheLines** [comment]
It worked, thanks for your fast help, saved the day :)
