### ISSUE TITLE
npm install can't find package.json

### ISSUE THREAD

**Issue by Foxly111** [RCVolus/lol-pick-ban-ui#174]
Hello! I've run into a problem where i download everything for the program and try to run it I always run into this massage:
![Screenshot_23](https://github.com/RCVolus/lol-pick-ban-ui/assets/141244919/dc85cdf5-9f45-4e8d-90e3-79cc97e7e147)

I used the program 2 years ago and it run smoothly.
Reinstalled everything today because of the updates and no matter what I try, I get this massage.

**Comment by sdomi4** [comment]
It looks like you aren't running the `npm install` command in the backend / layout folder. Take a look at the installation instructions here:
https://github.com/RCVolus/lol-pick-ban-ui#installation-development-purposes

**Comment by Foxly111** [comment]
oh wow you were right.
i just tried it thank you.
I saw a video where it didnt mention that and it worked for the guy
