### ISSUE TITLE
Do you have any plan for UI for LCK/LPL-Style 

### ISSUE THREAD

**Issue by SYNT4X54** [RCVolus/lol-pick-ban-ui#175]
We are looking for UI with LCK/LPL Style, but I couldn't found one. do you have plan for it?

**Comment by sdomi4** [comment]
We do not have any current plans to implement any additional UI styles.
Look at the [simple layout](https://github.com/RCVolus/lol-pick-ban-ui#installation-of-simple-layout) for a starting point to build a LCK-style UI.

**Comment by SYNT4X54** [comment]
okay. Hm is this updated version with new champion Naafiri?

**Comment by sdomi4** [comment]
The tool should automatically pull any new champion images. If you have any missing, try clearing the cache folder in the backed to force a redownload.
