### ISSUE TITLE
Multiple question.

### ISSUE THREAD

**Issue by SYNT4X54** [RCVolus/lol-pick-ban-ui#176]
1. How can I start again this program once I installed?

2. How can I change the logo on center?

3. How can I show the version of the in-Game?

**Comment by sdomi4** [comment]
1. Please refer to the readme: https://github.com/RCVolus/lol-pick-ban-ui#installation-development-purposes
2. Either replace the existing logo with your logo renamed or update `.\lol-pick-ban-ui\layouts\layout-volu-europe\src\europe\Overlay.jsx` with the new logo path
3. Modify `...\lol-pick-ban-ui\layouts\layout-volu-europe\src\europe\Overlay.jsx`
