### ISSUE TITLE
The system is not displaying the champions image correctly. Just Aatrox and Ahri.

### ISSUE THREAD

**Issue by MatheusMoon** [RCVolus/lol-pick-ban-ui#178]
![Screenshot_1](https://github.com/RCVolus/lol-pick-ban-ui/assets/81942432/47b4dd49-5c60-4b99-8269-d1a4cf9e35da)

**Comment by sdomi4** [comment]
That seems to be an issue with the asset download. Can you try clearing the datadragon cache by deleting the 13.20 folder in `...\lol-pick-ban-ui\backend\cache` and restarting the backend?

**Comment by MatheusMoon** [comment]
I redid the installation and it seems to have recovered the missing files, thank you!
