### ISSUE TITLE
Red side Spells Bug

### ISSUE THREAD

**Issue by MatheusMoon** [RCVolus/lol-pick-ban-ui#179]
Apparently the red side is having trouble getting the chosen spells to appear. He and I were using Flash + Ignite.

![image](https://github.com/RCVolus/lol-pick-ban-ui/assets/81942432/6dec967e-02dd-4b1e-8fd8-258d6bb403e2)

**Comment by sdomi4** [comment]
It looks like you are the Irelia in this scenario. As a player on the blue team, you don't get to see the red team's summoner spells.

**Comment by MatheusMoon** [comment]
If I'm just a spectator, should it work?

**Comment by sdomi4** [comment]
Yes, that's how the tool is intended to be used. It only receives the information you see in the lobby.

**Comment by MatheusMoon** [comment]
Wonderful, thank you!

![image](https://github.com/RCVolus/lol-pick-ban-ui/assets/81942432/53be300d-86d7-4105-90d5-c66e5769de4b)

**Comment by MatheusMoon** [comment]
Also, LoL_Prod_Toolkit Is it a combination of all these programs?

**Comment by sdomi4** [comment]
Im not sure which other programs you mean, the prod-toolkit also has (a very similar) overlay for champ select as well as a lot of other features: https://github.com/RCVolus/league-prod-toolkit/wiki
