### ISSUE TITLE
Error: ENOENT: no such file or directory, open './example.json'

### ISSUE THREAD

**Issue by ThisInsider** [RCVolus/lol-pick-ban-ui#18]
![image](https://user-images.githubusercontent.com/17685101/85752724-f1f35200-b70b-11ea-89b8-8929ac214cbb.png)

When starting the backend (`npm start` after `npm install`) this error occurs. Apparently a file example.json is missing, and I cannot start the backend server without it.
I've checked the code and WebSocketServer.sendHeartbeat method expects it.

I've also done all the installation steps as instructed in the Installation part.

My node version is v12.6.0

**Comment by LarsBaertschi** [comment]
Hey, thanks for reporting in!

Apologies, the issue is on our side. I have recently removed the file, because it shouldn't be used. I will check in tonight, expect a fix by then :)

Sorry for any inconvenience caused!

Best regards
Lars

**Comment by ThisInsider** [comment]
Thanks for the amazingly quick reply!
I can't wait to have fun with your program!

**Comment by LarsBaertschi** [comment]
Hey, was a bit busy. My latest commit should have fixed the issue:

https://github.com/RCVolus/lol-pick-ban-ui/commit/4ed4ad5ac4512b50dc189c12af7463509fd75626

Make sure to redownload and replace your local solution.

Thanks for your patience,
Lars

**Comment by ThisInsider** [comment]
Can confirm, everything is working!
Thanks!
