### ISSUE TITLE
it's not working in server garena

### ISSUE THREAD

**Issue by leanbinh** [RCVolus/lol-pick-ban-ui#22]
I can't connect to the LCU on the garena server, but on the LCU of the Server, which is under the control of Riot games, I can connect, I saw a friend using your pick board ui on the garena server
![image](https://user-images.githubusercontent.com/67872108/86985270-1561d680-c1bb-11ea-9557-c8541da9b4f5.png)

**Comment by LarsBaertschi** [comment]
Okay, that may be an issue. Could you please try to start the backend using this command (adapt the directory to the path were your League of Legends.exe (Client) is.

```npm start -- --leaguePath "C:\\Riot Games\League of Legends"```

**Comment by leanbinh** [comment]
> Okay, that may be an issue. Could you please try to start the backend using this command (adapt the directory to the path were your League of Legends.exe (Client) is.
> 
> `npm start -- --leaguePath "C:\\Riot Games\League of Legends"`

thanks

**Comment by AnVT9496** [comment]
> I can't connect to the LCU on the garena server, but on the LCU of the Server, which is under the control of Riot games, I can connect, I saw a friend using your pick board ui on the garena server
> ![image](https://user-images.githubusercontent.com/67872108/86985270-1561d680-c1bb-11ea-9557-c8541da9b4f5.png)

Hi Anh, Anh làm được chưa, có thể support em được không ạ, em start server ko chạy

**Comment by leanbinh** [comment]
Bác đã thử chạy cmd bằng admin chưa trên máy chủ của garena là phải chạy bằng admin

**Comment by AnVT9496** [comment]
Dạ em chạy cmd bằng quyền admin rồi, nhưng nó không start dc server localhost:8999 á anh, với cả anh chạy được simple_layout chưa

**Comment by AnVT9496** [comment]
À, em chạy được rồi, mà layout không khớp lắm,anh chỉnh CSS khớp chưa :( màn hình em 1300px

**Comment by nghiahungls93** [comment]
bác leanbình có gặp lỗi khi chạy layout europe như này k ạ
![loi](https://user-images.githubusercontent.com/76861610/103452370-2d955700-4d01-11eb-8dc9-371c7b3ac0d2.png)

**Comment by leanbinh** [comment]
> bác leanbình có gặp lỗi khi chạy layout europe như này k ạ
> ![loi](https://user-images.githubusercontent.com/76861610/103452370-2d955700-4d01-11eb-8dc9-371c7b3ac0d2.png)

Cho cmd hoặc Powersell chạy bằng quyền admin đi bác client ở server garena muốn can thiệp được thì phải có quyền admin còn các server khác thì k cần

**Comment by leanbinh** [comment]
> bác leanbình có gặp lỗi khi chạy layout europe như này k ạ
> ![loi](https://user-images.githubusercontent.com/76861610/103452370-2d955700-4d01-11eb-8dc9-371c7b3ac0d2.png)

install cái layout europe chưa

**Comment by nghiahungls93** [comment]
Bác cho zalo hoặc fb để tiện trao đổi với
