### ISSUE TITLE
How to enlarge splash art of champion and show spell when ban-pick

### ISSUE THREAD

**Issue by leanbinh** [RCVolus/lol-pick-ban-ui#23]
![image](https://user-images.githubusercontent.com/67872108/87073666-f8271980-c247-11ea-9fc7-b74b37c8cf27.png)

1. I have some problems that need your help
how can i change the section: result, team name in both LEC and simple layouts.
2. How to enlarge splash art of champion and show spell when ban-pick as above picture

**Comment by RIOT-Panko** [comment]
same +1

**Comment by LarsBaertschi** [comment]
1. https://github.com/RCVolus/lol-pick-ban-ui#configuration
2. You need to touch the code yourself, which needs some understanding of HTML, CSS and JS. The simple layout is meant to be a project template, where you can add and build up your own design. The summoner spells are available in https://github.com/RCVolus/lol-pick-ban-ui/blob/6e894d8d5056af117bf73136b995dd2ccb0f44d3/layouts/layout-simple/script.js#L45 in the object `pick` using `pick.spell1` and `pick.spell2`. For the europe layout, summoners are available and enabled per default. However, you may disable them in `config.json`. This is especially useful when you don't add any delay for offline matches.
