### ISSUE TITLE
help

### ISSUE THREAD

**Issue by justvayne** [RCVolus/lol-pick-ban-ui#25]
I am new to this, could you explain how to use it? I would appreciate

**Comment by LarsBaertschi** [comment]
Hey, please check out the Readme: https://github.com/RCVolus/lol-pick-ban-ui/blob/master/README.md

Everything is described there (how to install, how to configure, etc.) If you think there is something missing, let me know! :)

**Comment by PieterVanZyl-NWU** [comment]
Hey Lars, I'm just going to make a tutorial video on how to set this all up so people know how to do this. I'll let you know when it's up

**Comment by LarsBaertschi** [comment]
@PieterVanZyl-NWU awesome! Yeah, I'd be happy to link it! Let me kniw if you need anything!

**Comment by justvayne** [comment]
> Hey, please check out the Readme: https://github.com/RCVolus/lol-pick-ban-ui/blob/master/README.md
> 
> Everything is described there (how to install, how to configure, etc.) If you think there is something missing, let me know! :)

SyntaxError: Failed to construct 'WebSocket': The URL 'undefined' is invalid.   that comes out

**Comment by LarsBaertschi** [comment]
Make sure you open up the correct link as described in point 11: https://github.com/RCVolus/lol-pick-ban-ui#installation-of-europe-layout (you really need to have the ?backend=... in there, or else the frontend wouldn't know where to find the backend)

**Comment by justvayne** [comment]
oh thanks, i already did, if i want to use the simple overlay, like the png that appears there, would it be possible? or something like that lcs NA style

**Comment by LarsBaertschi** [comment]
closing this because it's stalled and not really an issue with the software, but rather with the documentation.
