### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by Nilox01** [RCVolus/lol-pick-ban-ui#27]
I'm sorry to bother you, but I need help using the user interface. Up to step 5, I did everything right. Now I don't understand how to start the backend via localhost. I couldn't open the app.js file from the node, so I couldn't open it in the browser. Can you explain step 6 a bit more in detail how I can use it in the end?

Thank you for programming such a user interface.
MfG Nilox

Sry, I'm still new to the area.

**Comment by LarsBaertschi** [comment]
Once you did step 5, you should have a Terminal (e.g. Powershell) open. There should be the Ascii-Art that shows lol-pick-ban-ui. Once you've done that, the backend installation is completed. Unfortunately, you can not directly access the backend. Therefore you need to also install the europe frontend component (the only one available currently). Just follow the steps here from 7 to 11. https://github.com/RCVolus/lol-pick-ban-ui#installation-of-europe-layout

After that, you should be able to open up the webpage, that you can also add to OBS/vMix/xSplit as web source and then you should see the content there, as soon as a pick-ban starts in your client.

**Comment by Nilox01** [comment]
Thank you for helping me so quickly.
If I start backend and frontend the frontend tell me that I open it with "http://localhost:3000/" but the description says http://localhost:3000?backend=ws://localhost:8999 to open the frontend as a website. 

When I open with "http://localhost:3000?backend=ws://localhost:8999": It loads permanently.

When I open with "http://localhost:3000/": I get this error

SyntaxError: Failed to construct 'WebSocket': The URL 'undefined' is invalid.
connect
http://localhost:3000/frontend-lib.js:83:23
PB.start
http://localhost:3000/frontend-lib.js:110:5
(anonymous function)
C:/Users/NLVDa/Desktop/lol-pick-ban-ui/layouts/layout-volu-europe/src/App.jsx:37
  34 |            setConfig(hb.config);
  35 |        });
  36 | 
> 37 |        Window.PB.start();
     | ^  38 |    }, []);
  39 | 
  40 |    console.log(globalState);
View compiled
▶ 13 stack frames were collapsed.
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.  Click the 'X' or hit ESC to dismiss this message.

**Comment by LarsBaertschi** [comment]
By "it loads permanently" I think you are meaning it is displaying a complete white page with no content?

This is actually expected behaviour, the page will be just empty if there is no draft in progress currently. But as soon as a draft starts in the league client, the interface should pop up with an opening animation.

You should really open up with the ?backend parameter set, since your frontend needs to know where it can contact the backend.

Best regards
Lars

**Comment by Nilox01** [comment]
Thanks for the kind help. Everything works now
