### ISSUE TITLE
name could not be edited

### ISSUE THREAD

**Issue by leanbinh** [RCVolus/lol-pick-ban-ui#28]
![image](https://user-images.githubusercontent.com/67872108/89594476-1d756a80-d87c-11ea-84de-f46dcb67e31d.png)
I tried to edit the name in the app.jsx file, but when I went to banpick it didn't show the name I changed

**Comment by LarsBaertschi** [comment]
What "name" are you referring to?

I assume the team names. In that case, in App.jsx is only a default, the real version is loaded from the config.json in the root directory. That one is easier to edit, and also it immediately reflects changes, so you could change them without having to restart the frontend every time.

Please let me know if this solved your issue, or if I did not understand correctly what you want.

**Comment by leanbinh** [comment]
thanks
