### ISSUE TITLE
simple layout issues

### ISSUE THREAD

**Issue by getwh1ted** [RCVolus/lol-pick-ban-ui#30]
the simple layout does not show pick and ban champs, timers and everything else is working
![image](https://user-images.githubusercontent.com/48430352/90202481-21eed580-ddde-11ea-9697-c7238db0b213.png)

**Comment by getwh1ted** [comment]
just need to change patch to 1.15.1, now working
![image](https://user-images.githubusercontent.com/48430352/90202884-47c8aa00-dddf-11ea-932c-aeb164991b0c.png)

**Comment by LarsBaertschi** [comment]
Yes. You can also change it to "latest" in that case it will always use the most recent patch.

**Comment by alexissosa88** [comment]
¿como lo instalas? ¿podrás ayudarme'
