### ISSUE TITLE
Loading Team names from external source

### ISSUE THREAD

**Issue by floh22** [RCVolus/lol-pick-ban-ui#34]
Hey, 
Im trying to automatically load team names and scores from an external source (remote server) that isnt the config file. I was wondering where I would have to implement changes in order for the backend to fetch those values from somewhere other than the config file. Either that or if I could change the location of the config file to the remote server all together.

Thanks for your help!

**Comment by LarsBaertschi** [comment]
Hey! You could either provide the config file trough a windows share. I remember we did that once and it seemed to work.

Another idea would be to synchronise the config file with an external server using a synchronisation software like SyncThing.

Last but not least, you could also directly modify the code that is fetching the data to fetch it from your respective server, e.g. using an HTTP endpoint.

To do that, you would mostly have to change code here:
https://github.com/RCVolus/lol-pick-ban-ui/blob/0ffb9baab425d09ff111b8da758dc24800c89daa/backend/websocket/WebSocketServer.ts#L70 (fetches the config file periodically and submits it to the frontend)
Further the config file is read here https://github.com/RCVolus/lol-pick-ban-ui/blob/17364506474c59a3363239d74cfd0c244db41b2a/backend/state/State.ts#L12 and here https://github.com/RCVolus/lol-pick-ban-ui/blob/17364506474c59a3363239d74cfd0c244db41b2a/backend/state/State.ts#L16 when champ select starts.

**Comment by floh22** [comment]
Perfect, thank you!
Ended up going with option 3 as that seemed like the smallest hassle.
