### ISSUE TITLE
Can't find how to edit the image from Redbull Itemania to something else

### ISSUE THREAD

**Issue by Mattgames0425** [RCVolus/lol-pick-ban-ui#36]
I realize this is likely an obvious fix but it's 4 am and I looked everywhere I could think.

**Comment by LarsBaertschi** [comment]
Hey, since you closed this. Were you able to solve your issue in the meanwhile?

For the record and for Google: here you can find find the logo you'd have to exchange https://github.com/RCVolus/lol-pick-ban-ui/blob/master/layouts/layout-volu-europe/src/assets/Logo_Itemania_2019.png

**Comment by Mattgames0425** [comment]
I was able to fix the issue (didn't realize I had to restart it)
 I've been having a small issue with getting the software to work after restarting my pc. Do I have to do npm install/start then npm install/start each time or do I only have to do npm start. when I only do start sometimes it dosn't work

**Comment by Mattgames0425** [comment]
sorry for a second comment but is their also a way to make the finished pick ban stay on the screen until it detects a new pickban (I am using it for a stream and wanted it to stay for analysis purposes)

**Comment by WarrenIsh** [comment]
@Mattgames0425 Hey, how did you manage to change the image, did you just replace the image with a different image or was their some coding that you had to change?

**Comment by LarsBaertschi** [comment]
> @Mattgames0425 Hey, how did you manage to change the image, did you just replace the image with a different image or was their some coding that you had to change?

no, you just replace the image file and then you should be good to go.
