### ISSUE TITLE
Simple Layout Not working

### ISSUE THREAD

**Issue by WarrenIsh** [RCVolus/lol-pick-ban-ui#37]
I followed your steps and managed to open the backend of the code perfectly fine. When I go to follow steps 7-10 this is where things don't go as smoothly. 

So if I run the "serve" command in the master folder "lol-pick-ban-ui-master and follow the localhost:5000 link I get the following: 
![image](https://user-images.githubusercontent.com/72856900/95972231-7cbea080-0e12-11eb-8385-db3066b5657c.png)

But if I run the "serve" command and follow you link http://localhost:5000/layouts/layout-simple/?backend=ws://localhost:8999 I get the following image
![image](https://user-images.githubusercontent.com/72856900/95972428-b7283d80-0e12-11eb-9e04-fefd4b01c5fa.png)

I understand the blank template, where do I go in order to edit the layouts and show the relevant information? I have looked through all the closed issues and open issues to get help, but everyone just says its working, there is no actual solution posted. Tried finding the video link that is supposed to walk us through this process, but there is none. 

Any help would be appreciated!

Thanks

**Comment by LarsBaertschi** [comment]
Hey!

Sadly such a walk trough video was unfortunately never finished.

Once you can see it open like you do, everything should be working correctly and you should see the picks&bans coming in once you join a pick&ban phase in the champselect.

Please note that you need to adapt it, which requires you to need some CSS, HTML and a little of JS knowledge. If you do not want to do this, you can still go with the layout-volu-europe layout which works out of the box :) just follow the required steps on the Readme.

If you have any other question(s) don't hesitate to ask!

**Comment by WarrenIsh** [comment]
Hey :D 

Thanks for letting me know. So I managed to get the players names to appear on the white image above, but there is nothing else. No champ splash when selected, no team names at the top, no timer or anything else. Just player names. I tried editing the names of the teams in the config.json file in the root folder, but it doesn't change or edit anything on the link. Can you let me know which files I need to edit in terms of the html and css.

Then with regards to the EU layout as I wanted to implement this first, I followed the steps from 1 -6 and everything went smoothly, it opened the right port which is fine. When I now follow steps 7 - 11, this is where the issue arises. 

When I run step 9 of the EU layout I get this feedback:
![image](https://user-images.githubusercontent.com/72856900/96472568-eaaf0180-1230-11eb-855d-586da1ed713a.png)

I then ran step 10 and received the following 
![image](https://user-images.githubusercontent.com/72856900/96472911-4f6a5c00-1231-11eb-9bce-91cec511dd01.png)

Which led to a web page being opened which showed:
![image](https://user-images.githubusercontent.com/72856900/96472977-66a94980-1231-11eb-9b48-ac4f52a787d6.png)
![image](https://user-images.githubusercontent.com/72856900/96473012-6e68ee00-1231-11eb-9bde-c37f2f569083.png)
![image](https://user-images.githubusercontent.com/72856900/96473044-74f76580-1231-11eb-831f-82c7ed13becb.png)

I also followed the link in the document " http://localhost:3000?backend=ws://localhost:8999 " and all I get is a blank page
![image](https://user-images.githubusercontent.com/72856900/96473129-8ccee980-1231-11eb-894a-2ff371bf5998.png)

I have tried to run the audit to fix the errors in the cmd prompt from earlier, but doesn't change the outcome. This is why I tried to focus on the simple layout, hoping that I could get that one working. 

Not sure if you need more details to try and find the solution of some sort, but any help would be really appreciated. Sorry for the inconvenience, but trying to improve the casting for our local league here in South Africa. 

Thanks for all the help in advance.

**Comment by WarrenIsh** [comment]
Hey, so I tested out the eu LoL setup while I was casting and it seems to be working, but the background in white, so dont know where I need to add an image to their to edit that or if there is some coding that I need to put in. In the middle I have the Red bull logo, so dont know how to edit that in order for it to change it, hopefully you can help :)

See below:
![image](https://user-images.githubusercontent.com/72856900/96494488-b6464000-1246-11eb-80a8-c69c76e04e23.png)

**Comment by LarsBaertschi** [comment]
You can find how to change the logo here:
https://github.com/RCVolus/lol-pick-ban-ui/issues/36

For the white background, I recommend you to put it in your broadcast application (e.g. OBS). There the background will be transparent, you can then put in the background whatever you want.

**Comment by WarrenIsh** [comment]
Hey thanks so much for the help. 

If you could just let me know which files I need to edit for the simple layout as I edited the config.json file but there were no changes on the chrome tab. 

Thanks once again.

**Comment by LarsBaertschi** [comment]
I don't know why you are still refering to the simple layout. You can edit team names, coaches, scores and set up some other things directly in the config.json. Please check out the readme for more precise instructions. Closing this because the simple layout is working as expected.
