### ISSUE TITLE
Cannot GET /

### ISSUE THREAD

**Issue by pixelorm** [RCVolus/lol-pick-ban-ui#43]
When I write: localhost:8999 in my browser, it show me: Cannot GET /

I've seen that they use my ipv6 to share but i dont have one..

How can i change it?

![Capture](https://user-images.githubusercontent.com/73257511/96788222-21b41d00-13c1-11eb-81a1-ac96fc64b6aa.JPG)
![Capture 2](https://user-images.githubusercontent.com/73257511/96788223-21b41d00-13c1-11eb-8c03-e5b9ba9d192e.JPG)

**Comment by LarsBaertschi** [comment]
Hey, everything is fine as-is. It is totally expected that you get this message there. Since this is only the backend component, it does not have anything that's visible. That's what you need a frontend component for. Just follow the installation instructions.
