### ISSUE TITLE
Issue with the EU overlay

### ISSUE THREAD

**Issue by MikeSpike345** [RCVolus/lol-pick-ban-ui#44]
I followed all the directions as closely as possible from 1-11 and when I open up localhost:3000 it says "SyntaxError: Failed to construct 'Websocket': The URL 'undefined' is invalid. 

Is there any way I can fix it?

**Comment by LarsBaertschi** [comment]
Yes, do not use the link that opens up directly, but instead use the link from the documentation. It should contain a `?backend=ws://localhost:8999` part.

**Comment by MikeSpike345** [comment]
Thanks so much! I got it working, have a great day :)
