### ISSUE TITLE
[Question] Does it also work with real-time live games like soloq or flex?

### ISSUE THREAD

**Issue by Gnaj** [RCVolus/lol-pick-ban-ui#46]
Hi everyone, does this work with real-time live games? lets say soloq or flex? or a need to spectate

**Comment by LarsBaertschi** [comment]
Hey!

It should also work to some extent when using it from outside of the spectator mode (e.g. as player), also in normal drafts and solo / flex queue games.

However, some information like summoner spells may not be available. Also you team will always show as blue team, while the enemy team will be the red team / right side.

Also we can't guarantee if and how it works. But feel free to try it out, and let us know if you run into any issues.
