### ISSUE TITLE
Error after TS compilation with EU UI

### ISSUE THREAD

**Issue by Abarn279** [RCVolus/lol-pick-ban-ui#49]
Hi, I'm having this error after TS compilation when trying to start the EU web app. I've pulled the latest on master so I believe the issue is still present.

Notably, in the console, TS says "compiled successfully". 

![Capture](https://user-images.githubusercontent.com/5130719/101061255-eb3bf700-3555-11eb-8f47-01c5ab22c604.PNG)

**Comment by Abarn279** [comment]
I'm using the default configuration on both sides - i.e. as is with no edits to the repo. 

The server has successfully started and is running, so I don't believe that's related.

**Comment by LarsBaertschi** [comment]
Hey, please make sure that you open up the correct link that is mentioned in the README, and not the one that opens up per default.
