### ISSUE TITLE
bug when use europe layout

### ISSUE THREAD

**Issue by nghiahungls93** [RCVolus/lol-pick-ban-ui#53]
Hi. I have followed your instructions. however, when it comes to starting up the europe layout, the error is shown below.
(I user client Garena Vietnam)
![loi](https://user-images.githubusercontent.com/76861610/103451979-2a986780-4cfd-11eb-81ac-c81978aacdb4.png)
help me fix it. thank you

**Comment by himbolee** [comment]
share the same issue with u

![image](https://user-images.githubusercontent.com/29186269/103554334-b5d65080-4ee9-11eb-9278-8fdd54740354.png)

**Comment by MrMythikk** [comment]
Mine reaches the same error as well.

**Comment by LarsBaertschi** [comment]
same issue as https://github.com/RCVolus/lol-pick-ban-ui/issues/38
