### ISSUE TITLE
Error when npm start

### ISSUE THREAD

**Issue by HeadenGx** [RCVolus/lol-pick-ban-ui#57]
Hi ! 

I got a problem with that simple layout :/

When i use npm start, i got that type of message. 
![image](https://user-images.githubusercontent.com/79291360/108441657-db2edc00-7255-11eb-925e-2f4ce36611f8.png)

What is the problem here ? I do not understand, hope u will help me ^^
Thanks !

**Comment by MarkL4YG** [comment]
I'm not really sure what is happening here 🤔
Did you try running the command in CMD instead of Powershell?
