### ISSUE TITLE
Typescript compilation issues

### ISSUE THREAD

**Issue by MarkL4YG** [RCVolus/lol-pick-ban-ui#59]
On fresh installations of the UI, the LCU broker cannot be started. The reason is that a breaking patch has been pushed to ``@types/fs-extra`` that removed some fields from the corresponding type definitions.

Pinning ``@types/fs-extra`` to version ``9.0.0`` appears to be a valid work-around for this.

// See https://github.com/FearNixx/vigilant-bans/issues/1 for the original issue filed with us.

**Comment by LarsBaertschi** [comment]
Thank you very much, good catch! And also thank you for the installer, it's quite cool. The issue should be fixed now.
