### ISSUE TITLE
Error loading Campion-Icons into the overlay

### ISSUE THREAD

**Issue by finncyr** [RCVolus/lol-pick-ban-ui#62]
![Screeen](https://i.ibb.co/G3JtFtZ/Unbenannt.png)

As you can see in the picture above, the Tool has problems loading the champion icons for the bans.

This occured to us in multiple instances of Prime League Tournament-Lobbys. We reinstalled all npm modules and made sure the DD Database was up to date.

Is there any known fix for this issue?

**Comment by LarsBaertschi** [comment]
Hmm, we're not aware of any issue around this. How it works behind the scenes, so maybe that can help you debug the issue:
1. on start of the backend, the configured (per default always the latest) patch version information is fetched from the data dragon, a service provided by riot that provides static data for League of Legends
2. It checks if the folder cache/{patch} exists, if this is the case it directly starts up
3. If it does not exist, all the assets (mainly images) are fetched and saved in the cache/{patch} folder
4. If a file does not download (e.g. it fails), then you should see an error in the downloading process. But if the folder was created either way, the file will not be redownloaded the next time. So the first step if you notice that an image is missing, is to check the current patch in cache/{patch} if the image is in there. Probably it will be missing, so from there you could either remove the cache directory (which will cause a redownload), or add the missing images manually. I recommend the first option.

If something fails while downloading, could you maybe provide the logs that contain the error? Then we can have a look at why it's happening.
