### ISSUE TITLE
errors doing npm install

### ISSUE THREAD

**Issue by jonasj95** [RCVolus/lol-pick-ban-ui#64]
Hi, i installed it successfully on my own PC and wanted to help a friend install it for streaming. When doing the first npm install in the root directory following warnings/errors occur:

```
npm WARN ws@7.4.4 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.4.4 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 642 packages in 2.495s
found 1 low severity vulnerability
  run npm audit fix to fix them, or npm audit for details
```

**Comment by LarsBaertschi** [comment]
Hey, I just published a fix to the main branch. Could you please download again, and try again and confirm that it's working?

**Comment by jonasj95** [comment]
still not working:
![Screenshot_153](https://user-images.githubusercontent.com/80636605/111661077-0124ad80-880f-11eb-9f08-fd5e62e8a137.png)
