### ISSUE TITLE
installation error ( npm start )

### ISSUE THREAD

**Issue by viroosky** [RCVolus/lol-pick-ban-ui#65]
![image](https://user-images.githubusercontent.com/63733950/111425619-b9f5ca00-86f3-11eb-9319-873b31c51347.png)

**Comment by viroosky** [comment]
I hope you can help soon

**Comment by LarsBaertschi** [comment]
Hey, I just published a fix to the main branch. Could you please download again, and try again and confirm that it's working?

**Comment by jordanisapple1999** [comment]
> Hey, I just published a fix to the main branch. Could you please download again, and try again and confirm that it's working?

I need your help
SyntaxError: Failed to construct 'WebSocket': The URL 'undefined' is invalid.
connect
http://localhost:3000/frontend-lib.js:83:23
PB.start
http://localhost:3000/frontend-lib.js:110:5
(anonymous function)
C:/lol-pick-ban-ui-master/lol-pick-ban-ui-master/layouts/layout-volu-europe/src/App.jsx:38
35 | setConfig(hb.config);
36 | });
37 |

38 | Window.PB.start();
| ^ 39 | }, []);
40 |
41 | console.log(globalState);
View compiled
▶ 13 stack frames were collapsed.
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error. Click the 'X' or hit ESC to dismiss this message.
![image](https://user-images.githubusercontent.com/67945889/111791844-3657fb00-88f6-11eb-8edd-b9db64facfb0.png)
