### ISSUE TITLE
SyntaxError: Failed to construct 'WebSocket': The URL 'undefined' is invalid.

### ISSUE THREAD

**Issue by jordanisapple1999** [RCVolus/lol-pick-ban-ui#66]
connect
http://localhost:3000/frontend-lib.js:83:23
PB.start
http://localhost:3000/frontend-lib.js:110:5
(anonymous function)
C:/lol-pick-ban-ui-master/lol-pick-ban-ui-master/layouts/layout-volu-europe/src/App.jsx:38
  35 |         setConfig(hb.config);
  36 |     });
  37 | 
> 38 |     Window.PB.start();
     | ^  39 | }, []);
  40 | 
  41 | console.log(globalState);
View compiled
▶ 13 stack frames were collapsed.
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.  Click the 'X' or hit ESC to dismiss this message.
![image](https://user-images.githubusercontent.com/67945889/111580214-c1979a80-87e9-11eb-8be9-b5f84fabbdee.png)

**Comment by jordanisapple1999** [comment]
I hop you can help soon!!!

**Comment by LarsBaertschi** [comment]
Make sure you follow the readme and open the URL that is mentioned there, and not the one that opens up automatically.

**Comment by yasstec** [comment]
Same issue for me ...
