### ISSUE TITLE
Ddragon problem

### ISSUE THREAD

**Issue by Demax121** [RCVolus/lol-pick-ban-ui#68]
I don`t know if it`s a common issue or I`m doing something wrong but when I install the package and type in npm start everyting is going smoothly until downloading data from DDragon. It starts downloading data then it stops in random place for example it has downloaded 70% and doesn`t move at all, I even waited for 2 hours thinking something is wrong with my internet then I stopped program removed folder etc. and Did everyting again and hello, it stopped at 21% and didn`t move at all for an hour.

**Comment by LarsBaertschi** [comment]
Hmm weird! Seems like the connection is interrupted and so it can't finish the download properly. Can you maybe try to get a stable connection while downloading the assets? (e.g. prefer cable over WLAN), and try again? Usually the download should finish within minutes.

**Comment by Demax121** [comment]
I've got stable internet connection, I don't use wifi to my PC that would
be a waste. Also I've found the solution, I used wireshark and It appears
the port was blocked.

pon., 19 kwi 2021, 14:31 użytkownik Larce | Lars Bärtschi <
***@***.***> napisał:
