### ISSUE TITLE
Summoners not showing "Layout Simple"

### ISSUE THREAD

**Issue by challenger087** [RCVolus/lol-pick-ban-ui#70]
Summoners not showing on the "Layout Simple" did i miss something ?

![vlcsnap-2021-03-28-20h33m50s552](https://user-images.githubusercontent.com/60705849/112763505-f9ca8480-9004-11eb-813a-0ca852fefa06.png)

**Comment by justinang1** [comment]
You need to manually code in the summoner spells. The starter code does not display them.

**Comment by challenger087** [comment]
> You need to manually code in the summoner spells. The starter code does not display them.

Can you please help me to do it or did you know someone who can do it for me ?

**Comment by justinang1** [comment]
Maybe - I would need your discord information or something else to communicate on as the fix is not easy (you will need to code some stuff). 

You need to edit the following files to get it to work: index.html, style.css, script.js. 

RCVolus might be able to provide a fix as well.

**Comment by justinang1** [comment]
![1](https://user-images.githubusercontent.com/18636212/112803524-3cea1f00-9028-11eb-8bc0-69ad7568f47a.png)

**Comment by challenger087** [comment]
I just edit the CSS file to change the color of the text and zoomed the splash images, the name of the team / score i hide them cause i have a program to change thoses info, much easy than everytime edit the "config.json" 
Here my Discord: MESA | Challenger#1468

**Comment by alexissosa88** [comment]
i need help whit this versión, pleaseeeeeeeeee! im not installing. The versión Europa its ok!

**Comment by ihabdz55** [comment]
some one please tell me how can i add summoners spells ? in the simple layout
