### ISSUE TITLE
Errors with npm Install... anything else i need to install first?

### ISSUE THREAD

**Issue by ozzykent** [RCVolus/lol-pick-ban-ui#71]
i do npm install this is all i get come up?? soz im new noob

PS C:\STREAM STUFFF\LoL PICK BAN UI\lol-pick-ban-ui-master> npm install
npm WARN ws@7.4.4 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.4.4 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 642 packages in 1.774s
found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
PS C:\STREAM STUFFF\LoL PICK BAN UI\lol-pick-ban-ui-master>

theres meant to be more come up then this..?

**Comment by MrTootToot** [comment]
Make sure you have installed the below before trying to install.

https://nodejs.org/dist/v10.16.3/node-v10.16.3-x64.msi

Love the stream by the way :)

**Comment by LarsBaertschi** [comment]
looks correct, this is only warnings that come up and that does not mean that something is not working properly.
