### ISSUE TITLE
Simple Layout

### ISSUE THREAD

**Issue by shinilee** [RCVolus/lol-pick-ban-ui#75]
![1](https://user-images.githubusercontent.com/82671596/115059171-2a8b3480-9eb4-11eb-8bac-7e96c56b3946.png)
![2](https://user-images.githubusercontent.com/82671596/115059200-35de6000-9eb4-11eb-8da4-9b1da76627c0.png)
![3](https://user-images.githubusercontent.com/82671596/115059246-48f13000-9eb4-11eb-9e21-765fbd6c5c37.png)

looks not right and doesn't show the champion when I create the league tournament game
layout-volu-europe working fine 
but layout-simple not working for me

do I have to do something else then enter npm install -g serve / serve ?

**Comment by justinang1** [comment]
If you drop your discord I can help you debug it. It might be an issue with the new patch (11.8.1), or you may be putting the underlay over the overlay in the html file.

**Comment by shinilee** [comment]
my discord is
https://discord.gg/jHGXDgB2
do I have to add or write anything in html file? because I have no idea about programing :(
