### ISSUE TITLE
Champion and Spells Images not loading.

### ISSUE THREAD

**Issue by pedrot94** [RCVolus/lol-pick-ban-ui#76]
Hi, I was able to succesfully run the LOL UI using the npm install --force command since it gave me an error on installation the first time I tried to run the program. Now is recognizing the League Client Match but when I pick champions to ban or to select most of them appear with a failed image icon as shown in the picture attached. Any thoughts on how to fix the issue?

![image](https://user-images.githubusercontent.com/14168489/116016847-81ef7a00-a603-11eb-9250-3355dad1b1d0.png)

**Comment by justinang1** [comment]
Are you using the following url: http://localhost:3000/?backend=ws://localhost:8999

Are there any other problems with the project? Console error messages, etc.?

**Comment by LarsBaertschi** [comment]
Hello, it seems like the images are not available locally. To fix this issue, try to delete the "cache" folder, and restart the backend component. This should cause it to download everything again.
