### ISSUE TITLE
error starting base directory

### ISSUE THREAD

**Issue by ManuelHenao** [RCVolus/lol-pick-ban-ui#8]
i got this:

`(node:7016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
(node:7016) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'port' of undefined
    at LeagueDataProviderService.getCurrentData (C:\Users\Manuel\Desktop\pickui\backend-build\data\league\LeagueDataProviderService.js:38:97)
    at TickManager.runLoop (C:\Users\Manuel\Desktop\pickui\backend-build\TickManager.js:18:61)
    at Timeout.timeout.setInterval [as _onTimeout] (C:\Users\Manuel\Desktop\pickui\backend-build\TickManager.js:15:47)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)`

**Comment by LarsBaertschi** [comment]
Hey! Another user noticed this issue recently. It seems to be related to the underlying library that detects where LoL is installed, which may be a regression issue due to the riot client changes that were done earlier this year. I'll look into that and add a possibility to supply an installation path soon!

Thank you for your report, leaving this open till fixed. Let me know if you find something out in the meanwhile.

**Comment by ManuelHenao** [comment]
Hi. Any Update? I really wats this on my stream :(

**Comment by LarsBaertschi** [comment]
Looking into this now, hope to provide a solution soon!

**Comment by LarsBaertschi** [comment]
I have done the following commit: https://github.com/RCVolus/lol-pick-ban-ui/commit/9fcfbebfd724321149a46b6d5241a1666af017b5

This allows to manually supply an installation directory for the league of legends client. Can you please try to supply it when starting like the following:

`npm run start -- --leaguePath [YOUR_LEAGUE_PATH]`

The default league path is C:\Riot Games\League of Legends on my system.

**Comment by ManuelHenao** [comment]
i tried but it dont changed idk if i entered it wrong.

https://i.imgur.com/PLgLWNy.png

**Comment by ManuelHenao** [comment]
i poened lol client and now i dont have the error, but doesnt happens nothing more.

https://i.imgur.com/Fxgs15U.png

And try to open LEC Layout and show this error

> SyntaxError: Failed to construct 'WebSocket': The URL 'undefined' is invalid.
> connect
> http://localhost:3000/frontend-lib.js:83:23
> PB.start
> http://localhost:3000/frontend-lib.js:110:5
> (anonymous function)
> C:/Users/Manuel/Desktop/aaaaa/lol-pick-ban-ui-master/layouts/layout-volu-europe/src/App.jsx:37
>   34 |         setConfig(hb.config);
>   35 |     });
>   36 | 
> > 37 |     Window.PB.start();
>      | ^  38 | }, []);
>   39 | 
>   40 | console.log(globalState);
> View compiled
> ▼ 13 stack frames were expanded.
> commitHookEffectListMount
> C:/Users/Manuel/Desktop/aaaaa/lol-pick-ban-ui-master/layouts/layout-volu-europe/node_modules/react-dom/cjs/react-dom.development.js:19607
> commitPassiveHookEffects
> C:/Users/Manuel/Desktop/aaaaa/lol-pick-ban-ui-master/layouts/layout-volu-europe/node_modules/react-dom/cjs/react-dom.development.js:19644
> HTMLUnknownElement.callCallback
> C:/Users/Manuel/Desktop/aaaaa/lol-pick-ban-ui-master/layouts/layout-volu-europe/node_modules/react-dom/cjs/react-dom.development.js:189
> invokeGuardedCallbackDev
> C:/Users/Manuel/Desktop/aaaaa/lol-pick-ban-ui-master/layouts/layout-volu-europe/node_modules/react-dom/cjs/react-dom.development.js:238
> invokeGuardedCallback
> C:/Users/Manuel/Desktop/aaaaa/lol-pick-ban-ui-master/layouts/layout-volu-europe/node_modules/react-dom/cjs/react-dom.development.js:291
> flushPassiveEffectsImpl
> C:/Users/Manuel/Desktop/aaaaa/lol-pick-ban-ui-master/layouts/layout-volu-europe/node_modules/react-dom/cjs/react-dom.development.js:22708
> unstable_runWithPriority
> C:/Users/Manuel/Desktop/aaaaa/lol-pick-ban-ui-master/layouts/layout-volu-europe/node_modules/scheduler/cjs/scheduler.development.js:656
> runWithPriority$1
> C:/Users/Manuel/Desktop/aaaaa/lol-pick-ban-ui-master/layouts/layout-volu-europe/node_modules/react-dom/cjs/react-dom.development.js:11076
> flushPassiveEffects
> C:/Users/Manuel/Desktop/aaaaa/lol-pick-ban-ui-master/layouts/layout-volu-europe/node_modules/react-dom/cjs/react-dom.development.js:22676
> (anonymous function)
> C:/Users/Manuel/Desktop/aaaaa/lol-pick-ban-ui-master/layouts/layout-volu-europe/node_modules/react-dom/cjs/react-dom.development.js:22555
> workLoop
> C:/Users/Manuel/Desktop/aaaaa/lol-pick-ban-ui-master/layouts/layout-volu-europe/node_modules/scheduler/cjs/scheduler.development.js:600
> flushWork
> C:/Users/Manuel/Desktop/aaaaa/lol-pick-ban-ui-master/layouts/layout-volu-europe/node_modules/scheduler/cjs/scheduler.development.js:556
> MessagePort.performWorkUntilDeadline
> C:/Users/Manuel/Desktop/aaaaa/lol-pick-ban-ui-master/layouts/layout-volu-europe/node_modules/scheduler/cjs/scheduler.development.js:160
> ▲ 13 stack frames were expanded.
> This screen is visible only in development. It will not appear if the app crashes in production.
> Open your browser’s developer console to further inspect this error.  Click the 'X' or hit ESC to dismiss this message.

**Comment by LarsBaertschi** [comment]
So,

a) it seems to be working for you now. And it also seems that you don't have to supply an installation path. It is normal that this doesn't do anything, since it waits for a champ select to start.
b) if you want to run the replay file, you never have to supply an installation path. So just use `npm start -- --data recordings/tournament-realm`.
c) correct way to supply the full installation path would be:
`npm start -- --leaguePath "C:\\Riot Games\League of Legends"`
d) As you can read in the README.md, you need to open the frontend like this: http://localhost:3000?backend=ws://localhost:8999 (Source: https://github.com/RCVolus/lol-pick-ban-ui#installation-of-europe-layout)

Does it work for you now?

**Comment by ManuelHenao** [comment]
It works!!!!!!! thanks

**Comment by ManuelHenao** [comment]
another question. where i can change team names and scores? i tried on src/app.jsx, but doent work.

**Comment by ManuelHenao** [comment]
an aditional note. i reinstalled on another path, and just tested npm start withouth path, but with client open, and it works. maybe that was the reason jaja and need say that on readme for idiots like me :)

**Comment by LarsBaertschi** [comment]
a) change them in the project root in the file `config.json`
b) so you didn't open the client? Alright, will add that just to be sure! Thanks for that feedback.

**Comment by ManuelHenao** [comment]
Hahaha, now im having a new code error

> (node:11020) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
>     at Function.values (<anonymous>)
>     at DataDragon.init (C:\UI LOL PIC BAN\backend-build\data\league\datadragon.js:67:33)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
>     at async main (C:\UI LOL PIC BAN\backend-build\app.js:40:5)
> (node:11020) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:11020) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

this is in backend. i dont know what i do, :( thi cose is after this:

> 2020-05-19T18:55:55.174Z [info ] datadragon  : Champion: 10.10.32161768608, Item: 10.10.32161768608, CDN: https://ddragon.leagueoflegends.com/cdn

**Comment by ManuelHenao** [comment]
i just deleted folder and installed it in another. but now i see cache folder isnot creating when i make the npm install, and i think this is the reason. but dont know what to do.

**Comment by LarsBaertschi** [comment]
Cannot reproduce. Please supply:
- Your config.json
- All other files you've changed
- The complete output of the log of the failing session

**Comment by ManuelHenao** [comment]
i dont change any file, im installing from 0 from the zip file.


> PS C:\lol-pick-ban-ui-master> npm start
> 
> > lol-pick-ban-ui@0.0.0 start C:\lol-pick-ban-ui-master
> > npm run build && node backend-build/app.js
> 
> 
> > lol-pick-ban-ui@0.0.0 build C:\lol-pick-ban-ui-master
> > tsc
> 
> 2020-05-19T19:29:32.595Z [info ] main        :   _          _       ____  ___   ____    _   _ ___
> 2020-05-19T19:29:32.596Z [info ] main        :  | |    ___ | |     |  _ \( _ ) | __ )  | | | |_ _|
> 2020-05-19T19:29:32.596Z [info ] main        :  | |   / _ \| |     | |_) / _ \/\  _ \  | | | || |
> 2020-05-19T19:29:32.596Z [info ] main        :  | |__| (_) | |___  |  __/ (_>  < |_) | | |_| || |
> 2020-05-19T19:29:32.596Z [info ] main        :  |_____\___/|_____| |_|   \___/\/____/   \___/|___|
> 2020-05-19T19:29:32.597Z [info ] main        :
> 2020-05-19T19:29:32.597Z [info ] main        : Configuration: {}
> 2020-05-19T19:29:32.597Z [info ] DataProviderService: Using League Client as data provider service.
> 2020-05-19T19:29:32.604Z [info ] LCUDataProviderService: Waiting for LeagueClient to connect
> 2020-05-19T19:29:32.605Z [info ] datadragon  : Getting latest versions from ddragon.
> 2020-05-19T19:29:33.572Z [info ] datadragon  : Champion: 10.10.32161768608, Item: 10.10.32161768608, CDN: https://ddragon.leagueoflegends.com/cdn
> (node:7544) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
>     at Function.values (<anonymous>)
>     at DataDragon.init (C:\lol-pick-ban-ui-master\backend-build\data\league\datadragon.js:67:33)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
>     at async main (C:\lol-pick-ban-ui-master\backend-build\app.js:39:5)
> (node:7544) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:7544) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by LarsBaertschi** [comment]
Can reproduce now, seems to be an issue with the data provider service. Looking into that soon!

**Comment by ManuelHenao** [comment]
yeah i think the same cuz i dont touch nothing when it worked.

**Comment by LarsBaertschi** [comment]
Alright, please check https://github.com/RCVolus/lol-pick-ban-ui/issues/9 for updates on that issue!
