### ISSUE TITLE
"UnhandledPromiseRejectionWarning" bug

### ISSUE THREAD

**Issue by RafaelLogan** [RCVolus/lol-pick-ban-ui#82]
I've followed all the procedures that the readme.MD says but every time I hit npm start "UnhandledPromiseRejectionWarning" loops
![image](https://user-images.githubusercontent.com/68531495/117464726-87de4700-af83-11eb-8c92-0de2c04c633c.png)

**Comment by morpheus26** [comment]
is also happening to me someone has a solution

**Comment by LarsBaertschi** [comment]
Hello, are you actually running the League of Legends-Client in the background? This error message usually says that a connection to the League Client could not be made.

**Comment by mpsb** [comment]
Hi, also facing this error. Are we supposed to have the League Client running?

**Comment by morpheus26** [comment]
yes the league of Legends-Client is running in the background

**Comment by LarsBaertschi** [comment]
So there seems to be a connection issue. Can you please let me know what server you are on?

**Comment by RafaelLogan** [comment]
I'm on the SEA server, it will not automatically connect even if it's on the background process. I've downgraded node.js but no go. I've given up on this and looked for other alternatives.

**Comment by RafaelLogan** [comment]
Update:
Right-click on the menu item and select Run as administrator.
if this doesn't work then it is not available with my league client

**Comment by morpheus26** [comment]
I am on the Brazilian server and also sometimes when this error does not appear, this other error appears in the browser
![erro](https://user-images.githubusercontent.com/83846619/118503090-afaa7900-b700-11eb-8122-31e73b1968da.png)

**Comment by RafaelLogan** [comment]
https://www.tenforums.com/tutorials/60177-add-open-powershell-window-here-administrator-windows-10-a.html
Here's how to make it run as administrator

**Comment by RafaelLogan** [comment]
![image](https://user-images.githubusercontent.com/68531495/118504844-76085b00-b75e-11eb-8feb-2cb956263dc1.png)

**Comment by morpheus26** [comment]
I did the whole process that you said I put the powershell in administrator mode but it looks just like your photo but it doesn’t advance to the last command line and gets stuck
![fica assim](https://user-images.githubusercontent.com/83846619/118508132-4711cb00-b705-11eb-9302-8599c98ab83a.png)

**Comment by RafaelLogan** [comment]
It's already started @morpheus26  you may now go to the other one.

**Comment by LarsBaertschi** [comment]
yes, @morpheus26 now you're good to go. The line that you saw above is in the middle somewhere, as long as it says "LeagueClient connected" at some point, it is fine.

**Comment by RafaelLogan** [comment]
hey, @LarsBaertschi where I can post the fix for this?

**Comment by LarsBaertschi** [comment]
Hello @RafaelLogan, I will update the README with that information. This was an issue in the past over and over again with certain servers (mostly servers not run by Riot Games)

**Comment by RafaelLogan** [comment]
Oh okay! Thank you!
