### ISSUE TITLE
URL Issue

### ISSUE THREAD

**Issue by UNknoWN8138** [RCVolus/lol-pick-ban-ui#92]
Hello! First of all, thank you so much for creating this. I am having a problem with the URL. I followed everything properly. But when I go to the URL, http://localhost:3000/?backend=ws://localhost8999, and open my client and start a tournament game mode, nothing appears on the URL.

![problem](https://user-images.githubusercontent.com/85313555/120700360-26f35180-c4e4-11eb-8474-6db761e69ae3.PNG)

**Comment by UNknoWN8138** [comment]
Also, I forgot to mention, my League client is in a Garena server.

**Comment by shinilee** [comment]
wrong address

http://localhost:3000?backend=ws://localhost:8999

that is the right address
