### ISSUE TITLE
TypeError: Cannot read property 'port' of undefined

### ISSUE THREAD

**Issue by DaBenjamins** [RCVolus/lol-pick-ban-ui#96]
![cmd_MSEn73Eq5a](https://user-images.githubusercontent.com/26729589/122138118-1613db80-ce14-11eb-8744-fbb94c744bad.png)

I am getting this error, and unable to find a way to resolve it.

**Comment by Tapiiri** [comment]
Same, followed the setup instructions and ended up with this error.
